{
  "predicates": [
    {
      "equals": {
        "method": "GET",
        "path": "/api/cars"
      }
    }
  ],
  "responses": [
    {
      "is": {
        "statusCode": 200,
        "headers": {
          "Content-Type": "application/json"
        },
        "body": {
          "results": []
        }
      }
    }
  ]
}