
POST http://localhost:2525/imposters
Content-Type: application/json

{
  "name":"Ex2GestaoInventario",
  "port":2222,
  "protocol":"http",
  "stubs":[
    {
      "responses":[{
        "is": {
          "statusCode":400,
          "headers":{"Content-Type":"application/json"},
          "body":{"error":"valor invalido"}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/produtos","method":"POST"}},
        {
          "equals":{
            "body":{
              "quantidade":-5
            }
          }
        }
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":201,
          "headers":{"Content-Type":"application/json"},
          "body":{"mensagem":"produto add com sucesso","id":3}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/produtos","method":"POST"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":200,
          "headers":{"Content-Type":"application/json"},
          "body":[
            {"id":1,"nome":"Teclado","preco":49.99,"quantidade":10},
            {"id":2,"nome":"rato descontinuado","preco":19.99,"quantidade":0}
          ]
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/produtos","method":"GET"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":200,
          "headers":{"Content-Type": "application/json"},
          "body":{"id":1,"nome":"teclado","preco":49.99,"quantidade":10}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/produtos/1","method":"GET"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":200,
          "headers":{"Content-Type":"application/json"},
          "body":{"mensagem":"stock updated","nova_quantidade":15}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/produtos/1/stock","method":"PUT"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":404,
          "headers":{"Content-Type":"application/json"},
          "body":{"erro":"produto inexistente"}
        }
      }],
      "predicates":[
        {"contains":{"path":"/api/produtos/999"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":200,
          "headers":{"Content-Type":"application/json"},
          "body":{"mensagem":"produto descontinuado removido"}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/produtos/2","method":"DELETE"}}
      ]
    },
    {
      "responses":[{
        "is":{
          "statusCode":400,
          "headers":{"Content-Type":"application/json"},
          "body":{"erro":"n e possivel remover, produto ainda tem stock disponivel"}
        }
      }],
      "predicates":[
        {"equals":{"path":"/api/produtos/1","method":"DELETE"}}
      ]
    }
  ]
}


###


#listar todos os produtos
GET http://localhost:2222/api/produtos
Content-Type: application/json

###

#ver detalhes de um produto especifico (produto 1)
GET http://localhost:2222/api/produtos/1
Content-Type: application/json


###

#criar produto com quantidade negativa (Erro)
POST http://localhost:2222/api/produtos
Content-Type: application/json

{
  "nome":"monitor",
  "preco":100.99,
  "quantidade":-5
}


###

#criar produto com sucesso
POST http://localhost:2222/api/produtos
Content-Type:application/json

{
  "nome":"monitor",
  "preco":105.99,
  "quantidade":20
}


###

#atualizar stock do produto 1 (PUT)
PUT http://localhost:2222/api/produtos/1/stock
Content-Type: application/json

{
  "quantidade":5
}


###

#tentar mexer num produto que n existe (produto 999)
GET http://localhost:2222/api/produtos/999
Content-Type: application/json


###

#tentar apagar produto c stock (produto 1 tem 10 unidades) erro
DELETE http://localhost:2222/api/produtos/1
Content-Type: application/json


###

#apagar produto c stock a zero (produto 2 tem 0 unidades) sucesso
DELETE http://localhost:2222/api/produtos/2
Content-Type: application/json